# Generated by Django 3.2 on 2022-01-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='info',
            field=models.CharField(db_index=True, default=21, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, default=21, max_length=50),
            preserve_default=False,
        ),
    ]
