# Generated by Django 3.2 on 2022-01-19 20:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0005_alter_blog_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='info2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Açıklama 2:'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='info3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Açıklama 3:'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='info4',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Açıklama 4:'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='red',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Kırmızı Alan:'),
        ),
    ]
