# Generated by Django 3.2 on 2022-01-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0007_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_image',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='Tittle resim:'),
        ),
    ]
