# Generated by Django 3.2 on 2022-01-23 14:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0008_blog_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='black',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='category',
            name='image2',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='category',
            name='image3',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='category',
            name='info2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='personel',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='category',
            name='personel_info',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='category',
            name='title2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
