# Generated by Django 3.2 on 2022-01-23 14:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0009_auto_20220123_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
