# Generated by Django 3.2 on 2022-01-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0010_category_title_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_info',
        ),
        migrations.AddField(
            model_name='category',
            name='title_infor',
            field=models.CharField(db_index=True, default=21, max_length=200),
            preserve_default=False,
        ),
    ]
