# Generated by Django 3.2 on 2022-01-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0011_auto_20220123_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title_infor',
            new_name='title_info',
        ),
    ]
