# Generated by Django 3.2 on 2022-01-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0012_rename_title_infor_category_title_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='title2',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
