# Generated by Django 3.2 on 2022-01-23 16:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0013_auto_20220123_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='personel_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
