# Generated by Django 3.2 on 2022-01-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0014_alter_category_personel_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image3',
        ),
    ]
